cmd/brew-which-formula.rb
cmd/brew-which-update.rb
executables.txt

Per https://github.com/Homebrew/homebrew-command-not-found/commit/a5e5510318056381d050d9ebdde1b27828db3c5f
cc @bfontaine

store short name directly in executables.txt

---

README.md

README.md: Add Bash v4 config steps

---

Cookbook.md
cmd/brew-which-update.rb

`brew which-update` now fetch the bottles of missing formulae to make the update process easier.

Automatically fetch bottles

---

README.md

Replaces badge for Azure Pipelines.

README: use GitHub Actions badge.

---

cmd/which-formula.rb

Make use of new helper from https://github.com/Homebrew/brew/pull/7120. Can't be merged until that PR has been released in a tag.

Use cli/parser min_named helper

---

README.md
cmd/brew-command-not-found-init.rb

My first PR! Sorry if there is any mistake. This fixes slow shell startup time. I used @bfontaine's solution -- https://github.com/Homebrew/homebrew-command-not-found/issues/56#issuecomment-569901106

Fix long shell startup time

---

Rakefile
cmd/which-formula.rb
cmd/which-update.rb
lib/executables_db.rb
lib/which_formula.rb

Broke after Homebrew/brew#8144.
Also fix `brew style`.

cmd: fix for Homebrew.args changes

---

cmd/which-update.rb
lib/which_update.rb

I missed the usage of `Homebrew.args` in `lib/which_update.rb`.

Fix which-update arg passing.

---

lib/which_formula.rb

Needed for https://github.com/Homebrew/brew/pull/10750

Fix brew style

---

.github/workflows/update-database.yml
lib/executables_db.rb

Setup @BrewTestBot as the `git` user for the scheduled database updates.
Also, remove a debug line that I forgot to remove in #77

Setup git user for scheduled database updates

---

.github/workflows/update-database.yml
executables.txt

Reverted commits:
* workflows/update-database: add runner to workflow options (b295cec6fb375c5e5d27d2d7fba5818051c4b7bd)
* Add alsa-lib, apt, at-spi2-atk and 40 more (b7853d0bdd2c7edc6b596ed75b93b5873602e8d1)
See https://github.com/Homebrew/homebrew-command-not-found/pull/80#issuecomment-822012582

Revert Linux database update

---

Rakefile
handler.fish

The handler function for fish is (mostly) written almost six years ago and looks unnecessarily complex today. This PR aims to make it modern and simpler.
Details about the changes will be later added as inline comments.

Simplify Fish handler

---

lib/executables_db.rb

For https://github.com/Homebrew/brew/pull/16501.

Fix RuboCop `Style/RedundantFreeze` offenses

---

cmd/which-formula.rb
cmd/which-update.rb

Some minor formatting & wording fixes for the manpage.

manpage: minor formatting & wording fixes

---

lib/which_formula.rb

- For https://github.com/Homebrew/brew/pull/16745.

Fix RuboCop `Performance/MapCompact` offenses

---

lib/which_update.rb

For https://github.com/Homebrew/brew/pull/16848

Use RuboCop default hash syntax.

---

.github/workflows/tests.yml

Need to cleanup existing cruft to install bash/fish.

workflows/tests: fix CI job.

---

cmd/command-not-found-init.rb
cmd/which-formula.rb
cmd/which-update.rb

This is a nicer format and will get analytics.

cmd/*: migrate to AbstractCommand

---

cmd/command-not-found-init.rb

Follow up from some `require` removals in Homebrew/brew

Add missing require

---

.github/workflows/update-database.yml

For https://github.com/orgs/Homebrew/security/campaigns/1.

workflows/update-database: fix zizmor findings

---

README.md

Make `__hb_cnf_handler` a local and private variable.

README: more idiomatic fish instructions
