README.md
cmd/brew-command-not-found-init.rb

This helps to simply the shell source command.

add brew-command-not-found-init command

---

README.md

Bash 4.x is required but this wasn't mentioned in the readme. This may address https://github.com/Homebrew/homebrew-command-not-found/issues/27 and https://github.com/Homebrew/homebrew-command-not-found/issues/26

README update bash

---

README.md

If the command is not installed, the old command still printed out
command not found error.

Fix command detection printing error

---

handler.sh

According to http://zsh.sourceforge.net/Doc/Release/Command-Execution.html
It's not clear if zsh used to print the error itself, like https://bugzilla.redhat.com/show_bug.cgi?id=1358372 seems to suggest, but the latest version of zsh doesn't, and is documented as such.

Add error message for zsh

---

handler.sh

This should fix #41.
I successfully tested with Zsh 5.2 and 5.3.1.

zsh: don't duplicate error messages on older version

---

cmd/brew-which-formula.rb

The method was removed in Homebrew/brew@b70b542.

Remove deprecated `default_formula?` check

---

README.md
cmd/which-formula.rb
lib/executables_db.rb

- The most recent two macOS versions have Zsh as their default shell.

README: Remove outdated Bash upgrade instructions

---

Rakefile

Incorrectly added by `brew style` (fixed in https://github.com/Homebrew/brew/pull/10469).

Rakefile: remove environment.

---

.github/workflows/scheduled.yml
cmd/which-update.rb
lib/executables_db.rb
lib/which_formula.rb
lib/which_update.rb

This PR attempts to create a scheduled workflow to update the database using `brew which-update`.
It adds a new `--install-missing` option to `which-update` which will install missing formulae (i.e. those that are `bottle :unneeded`) that wouldn't otherwise be updated.
For now, I decided to run this on both macOS and Linux, each time once a day. It's probably overkill to run it on each but some formulae that are only available on one platform would otherwise be missed.
Edit: I realized that we probably don't want two jobs doing mostly the same thing running at the same time because they will both changes. For now, I changed to only run on macOS. I think this will cover most cases and, as always, specific linux-only instances can be managed manually if needed. If automating on Linux is …

Add scheduled workflow to update database

---

.github/workflows/update-database.yml
cmd/which-update.rb
lib/executables_db.rb
lib/which_update.rb

Rename the workflow to better explain what it's doing. Also, add a `--max-downloads` flag to `which-update` so that the number of formulae updated per-run can be limited for manual invocations.

Fix automatic database updates

---

.github/workflows/update-database.yml

This tries to fix the issue with PRs from #79. There, the workflow would be run from the non-`master` PR branch. Part of this run would checkout that branch, commit the changes, and then push to master. This meant that the PR commits were pushed directly, causing a fast-forward merge. This is undesirable. Now, the changes will be applied only to the master branch so the push doesn't include any PR commits.
While modifying that file, I also added the ability to use Linux to run the workflow if desired. This will not happen by default, but could be manually done.

Fix database update workflow and allow linux runs

---

executables.txt
lib/executables_db.rb

I noticed when running `which-update` locally that `mosquitto` seemed to be handled differently based on whether it was checked from a bottle or from the install prefix. It turns out that the reason for this difference was that the `sbin` directory was being checked in `update_installed_formula` but not in `update_bottled_formula`. The login in `update_bottled_formula` allows for `sbin` paths to be used, but doesn't actually list any because of the pattern used for the `tar` command. This PR adds an `sbin` pattern to that `tar` command to list both `bin` and `sbin` paths to be checked for binaries.
CC @bfontaine to be sure that this is a bug and not intentional

lib/executables.db: check bottle's sbin directory for executables

---

.github/workflows/update-database.yml

This PR attempts to help diagnose and fix the issue where PRs are merged when running the workflow.
I've temporarily removing the push item so this won't be merged too soon

workflows/update-database: Don't merge PRs when running

---

lib/executables_db.rb
lib/which_update.rb

Disabled formulae can't be installed so we should remove them from the database so they're not recommended to users to install.

lib/executables_db: remove disabled formulae when updating

---

handler.fish
handler.sh

Fixes https://github.com/Homebrew/homebrew-command-not-found/issues/110
This PR changes the handler to simply ignore `-h`, `--help`, `--usage` and `-?` instead of passing these commands off to `brew which-formula`. These four options are the possible [help flags that are defined in `brew.rb`](https://github.com/Homebrew/brew/blob/89cf96fffac2aeb37ca4429a5afa09fe43c995e1/Library/Homebrew/brew.rb#L32), and passing them to `brew which-formula` will display the help text immediately before even getting to the execution of the `which-formula` command.

Handler: ignore `-h`, `--help`, `--usage`, and `-?`

---

lib/which_formula.rb

- I actually did the benchmarking in this TODO, with Ruby's `Benchmark`.
```
Benchmark.bm do |bm|
bm.report(:ruby) { File.readlines(LIST_PATH).map(&:chomp).select { |line| line.include?(cmd) } }
bm.report(:grep) { Utils.popen_read("grep", "--color=never", cmd, LIST_PATH).chomp.split("\n") }
end
```
gave the answer that:
```
❯ brew which-formula hello
user     system      total        real
ruby  0.004031   0.000221   0.004252 (  0.004249)
grep  0.000073   0.001532   0.005908 (  0.006125)
❯ brew which-formula automysqlbackup
user     system      total        real
ruby  0.002353   0.000284   0.002637 (  0.002651)
grep  0.000050   0.001095   0.005897 (  0.006248)
```

WhichFormula: Use Ruby, not `grep`, for searching the formulae file

---

cmd/which-update.rb
lib/executables_db.rb
lib/which_update.rb

Instead, collect all formulae from their taps, then load them explicitly via `Formulary`.
This should fix #133.

executables_db: avoid `Formula#all`

---

lib/executables_db.rb

Fixes: #137
Supercedes: #138
This PR fixes the formula loading method in `executables_db` to call the appropriate `Formulary` method. `Formulary::load_formula_from_path` only loads the formula's class into the `Formulary` namespace, but doesn't actually return an initialized formula instance. Also, this method won't work for API installs if the `homebrew/core` tap isn't installed.
Also, this should hopefully fix the CI failures that have resulted in the database not being updated in ~150 days 😅
CC: @woodruffw and @olfway

Fix which-update formula loading

---

cmd/which-formula.rb
cmd/which-update.rb
handler.sh

While fixing `brew style` tap support (https://github.com/Homebrew/brew/pull/17482), brew CI surfaced some style issues in this tap. This fixes style issues but there are still a number of shellcheck issues in `handler.sh` that need to be handled in some way (either through fixes or disabling unwanted rules):
```
In /opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh line 12:
if ! which brew >/dev/null; then return; fi
^---^ SC2230 (info): 'which' is non-standard. Use builtin 'command -v' instead.
In /opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh line 22:
if test -z "${CONTINUOUS_INTEGRATION}" && test -n "${MC_SID}" -o ! -t 1
^-----------------------^ SC2154 (warning): CONTINUOUS_INTEGRATION is referenced but not assigned.
^-------^ SC2154 …
```

Fix style issues

---

.github/workflows/update-database.yml

`shellcheck` is reporting an SC2086 ("Double quote to prevent globbing and word splitting") issue in the `update-database.yml` workflow. This adds quotes around the related area to resolve the issue.
There are other shellcheck issues in `handler.sh` but I figured that was best left to someone who's familiar with the file and/or better at shell scripting:
```
In /opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh line 12:
if ! which brew >/dev/null; then return; fi
^---^ SC2230 (info): 'which' is non-standard. Use builtin 'command -v' instead.
In /opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh line 22:
if test -z "${CONTINUOUS_INTEGRATION}" && test -n "${MC_SID}" -o ! -t 1
^-----------------------^ SC2154 (warning): CONTINUOUS_INTEGRATION is …
```

Fix shellcheck issues in workflows

---

.github/workflows/tests.yml
handler.sh

- Fix or disable various shellcheck warnings
- Use `is-at-least` from ZSH to compare version strings properly
While we're here:
- cleanup the CI job and improve the variable name/usage
Needed for https://github.com/Homebrew/brew/pull/17482

brew style fixes

---

.github/workflows/update-database.yml

- fix quoting as, without this, the job will always fail.
- test this workflow on all branches so it doesn't get broken again.

workflows/update-database: various fixes.

---

.github/workflows/update-database.yml

Avoid using input expanded with the `${{ .. }}` syntax in shell scripts to prevent code injection.

workflows/update-database: handle input string more robustly

---

.github/workflows/tests.yml
cmd/command-not-found-init.rb
cmd/which-formula.rb
cmd/which-formula.rbi
cmd/which-update.rb
cmd/which-update.rbi
lib/executables_db.rb
lib/which_formula.rb
lib/which_formula.rbi
lib/which_update.rb
lib/which_update.rbi

- In our bid to make all official taps Sorbet typed (https://github.com/Homebrew/brew/issues/17297), let's do another quick one.

Basic Sorbet `typed: true`

---

.github/workflows/update-database.yml

This helps with transparency and they get updated by Dependabot.

workflows: use full version numbers

---

README.md

The image is 404ing and it doesn't really add value.

README: remove GitHub Actions badge

---

.github/workflows/update-database.yml

This is a good "canary" case for making sure SSH signing goes smoothly.

update-database: switch to SSH signing

---

.github/workflows/update-database.yml

Since this runs on `macos-latest`, use `shasum -a 256` instead of `sha256sum`.
Also, there's no reason we need to write our own error message, so let's drop `--check` and just use the built-in one. It still errors with a non-zero exit code on checksum failure

Fix GitHub Packages checksum calculation

---

.github/workflows/tests.yml

Potential fix for [https://github.com/Homebrew/homebrew-command-not-found/security/code-scanning/9](https://github.com/Homebrew/homebrew-command-not-found/security/code-scanning/9)
To fix the problem, add a `permissions` block to the workflow to explicitly set the minimum required permissions for the `GITHUB_TOKEN`. Since the workflow only installs dependencies, validates shell syntax, and runs tests, it does not require any write permissions. The most restrictive and appropriate setting is likely `contents: read`, which allows the workflow to read repository contents if needed, but not to write or modify anything. This block should be added at the top level of the workflow (just after the `name:` and before `on:`), so it applies to all jobs unless overridden.
---
_Suggested fixes powered …

Potential fix for code scanning alert no. 9: Workflow does not contain permissions

---

.github/workflows/update-database.yml

Bumps the all group with 1 update: [actions/checkout](https://github.com/actions/checkout).
Updates `actions/checkout` from 4.2.2 to 5.0.0
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v4.2.2...08c6903cd8c0fde910a37f88322edcfb5dd907a8)
---
updated-dependencies:
- dependency-name: actions/checkout dependency-version: 5.0.0 dependency-type: direct:production update-type: version-update:semver-major dependency-group: all ...

Bump actions/checkout from 4.2.2 to 5.0.0 in the all group

---

lib/executables_db.rb
lib/which_update.rb

After https://github.com/Homebrew/brew/pull/20525, some modifications are needed for the `o*` output methods to work correctly.
This should fix the failing DB job

Use `utils/output` for `o*` output methods

---

cmd/command-not-found-init.rb
cmd/which-formula.rb
cmd/which-update.rb
cmd/which-update.rbi
executables.txt
lib/executables_db.rb
lib/which_formula.rb
lib/which_update.rb

This will eventually be needed when this command is merged into Homebrew/brew, but we may as well start now to help with any changes needed until then.
In order to get to `typed: strict` cleanly, I needed to refactor a few things:
- I created a `FormulaEntry` struct to store formula version/binary pairs more cleanly than a tuple or array
- I created a `Changes` class to replace the hash of sets for more clean access
Either of those can be dropped if desired.
Also, for some reason there was one entry in the current database (`valgrind`) that did not yet have a version associated. This likely means that the scheduled job has never installed this formula before. To avoid needing to handle the case where there is no version, I just manually added version `1.0.0`. Since `valgrind` is currently …

Enable `typed: strict`

---

.github/workflows/update-database.yml

Follow-up to https://github.com/Homebrew/homebrew-command-not-found/pull/277
If we run on all pull requests, there's no need to also run on pushes to any branch. We should restrict this to `main` branch pushes

Only run `update-database` on pushes to the main branch

---

.github/workflows/update-database.yml

Follow-up to #278
Fix the update database workflow. Turns out this was a simple working directory mismatch issue :facepalm:
Now that we're not committing to the repository, no need to do a manual checkout and we can just let `set-up-homebrew` handle it.
Also, let's upload the database as an actions artifact so we can have some sort of historical record (maybe this should eventually be moved to GitHub Packages, but let's figure that out later)

Fix working directory issue with update database workflow

---

lib/which_formula.rb

Follows https://github.com/Homebrew/homebrew-command-not-found/issues/108#issuecomment-3299823648, this PR sets a max-time to brew download command in the handler for normal users. This PR does not affect CI runs.

Set a max-time to brew download command in the handler

---

lib/which_formula.rb

As per the PR title, set `retries = 0` for no retry.
- This PR requires: Homebrew/brew#20722

Fix curl no retry by set `retries = nil`
